name: Deploy App Service 

on: workflow_dispatch

env:
  AZURE_WEBAPP_NAME: as-movie-demo
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Building App
      run: dotnet build --no-restore
    - name: Unit Tests
      run: dotnet test --no-build --verbosity normal --filter 'FullyQualifiedName!~IntegrationTests'
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish/${{ env.AZURE_WEBAPP_NAME }}'
    - name: Upload Artefacts
      uses: actions/upload-artifact@v2
      with:
        name: '${{ env.AZURE_WEBAPP_NAME }}-${{ github.run_id }}'
        path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Fetch Artifacts
      uses: actions/download-artifact@v2
      with:
        name: '${{ env.AZURE_WEBAPP_NAME }}-${{ github.run_id }}'

    - name: Deploy Application
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_MOVIE_DEMO  }} 
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME }}'