on: workflow_dispatch
name: Deploy To Container Instance

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest

      steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Build and push image'
        uses: azure/docker-login@v3
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          build-args: |
            "OMDB_APP_KEY=${{ secrets.OMDB_APP_KEY }}"
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/moviedemo:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/moviedemo:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: rg-movie-demo
          dns-name-label: rg-movie-demo${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/moviedemo:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: movie-demo-container-instance
          location: 'eastus'
          cpu: .5
          memory: 1.5