name: Provision App Service

on: workflow_dispatch

jobs:
  tf_plan_and_apply:
    uses: davidomahony/SharedDeployment/.github/workflows/tfplan_apply.yml@main
    with:
      terraform_directory: "infra/AppService"
      terraform_version: '0.14.8'
      environment: dev
    secrets: inherit