name: Provision App Service

on: workflow_dispatch

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.TF_VAR_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANTID }}

    defaults:
      run:
        shell: bash
        working-directory: infra/AppService

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color


  terraform_apply:
    name: Terraform Apply
    needs: terraform_plan
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.TF_VAR_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANTID }}
    environment:
      name: dev
    defaults:
      run:
        shell: bash
        working-directory: infra/AppService

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

