name: Provision App Service

on: workflow_dispatch

jobs:
  tf_plan_and_apply:
    uses: davidomahony/SharedDeployment/.github/workflows/tfplan_apply.yml@main
    with:
      terraform_directory: "infra/AppService"
      terraform_version: '0.14.8'
      environment: dev



# jobs:
#   terraform_plan:
#     name: Terraform Plan
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@master

#       - name: Terraform Plan
#         uses: davidomahony/SharedActions/actions/TerraformPlan@v0.0.1
#         with:
#           directory: ${{ env.terraform_directory }}
#           tf_version: ${{ env.terraform_version }}

#   terraform_apply:
#     name: Terraform Apply
#     needs: terraform_plan
#     runs-on: ubuntu-latest

#     environment:
#       name: dev

#     steps:
#       - name: Checkout
#         uses: actions/checkout@master

#       - name: Terraform Plan
#         uses: davidomahony/SharedActions/actions/TerraformApply@v0.0.1
#         with:
#           directory: ${{ env.terraform_directory }}
#           tf_version: ${{ env.terraform_version }}

